package com.example.demo.user;

import com.example.demo.movie.Movie;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name="users")
public class User {
    @Id
    @SequenceGenerator(
            name = "user_sequence",
            sequenceName = "user_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.IDENTITY,
            generator = "user_sequence"
    )
    // ID should be generated by the backend, not received from the frontend
    private Integer id;
    private String firstName;
    private String lastName;
    private String email;
    private String userName;
    private String password;
    @ManyToMany
    @JoinTable(
        name = "wishlist",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "movie_id")
    )
    private Set<Movie> wishlist;

    @ElementCollection
    private Set<Integer> blocked_users = new HashSet<>();

    public User() {}

    public User(Integer id,
                String firstName,
                String lastName,
                String email,
                String userName,
                String password) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.userName = userName;
        this.password = password;
        this.wishlist = new HashSet<>();
        this.blocked_users = new HashSet<>();
    }

    public void updateUser(User user) {
        this.firstName = user.getFirstName();
        this.lastName = user.getLastName();
        this.email = user.getEmail();
        this.userName = user.getUserName();
        this.password = user.getPassword();
        this.wishlist = user.getWishlist();
        this.blocked_users = user.getBlocked_users();
    }

    @Transient //- transient means we can ignore this from the database
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Movie> getWishlist() {
        return wishlist;
    }

    public void addToWishlist(Movie movie) {
        this.wishlist.add(movie);
    }

    public void removeFromWishlist(Movie movie) {
        this.wishlist.remove(movie);
    }

    public void setWishlist(Set<Movie> wishlist) {
        this.wishlist = wishlist;
    }

    public Set<Integer> getBlocked_users() {
        System.out.println(this.blocked_users);
        return this.blocked_users;
    }

    public void setBlocked_users(Set<Integer> blocked_users) {
        this.blocked_users = blocked_users;
    }

    public void addToBlocked_users(Integer user_id) {
        this.blocked_users.add(user_id);
    }

    public void removeFromBlocked_users(Integer user_id) {
        this.blocked_users.remove(user_id);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
